### ISSUE TITLE
Image sources

### ISSUE THREAD

**Issue by mprinc** [bast/git-rebase-squash-exercise#1]
Hi everyone,

where are the sources of images in `git-rebase-squash-exercise/img/` for example: [rebase haiku](https://raw.githubusercontent.com/bast/git-rebase-squash-exercise/master/img/rebase-exercise-1.jpg) ?

or which tool did you use to create them

Thanks

**Comment by bast** [comment]
Dear Sasha, sources are here: https://github.com/coderefinery/git-branch-design/tree/gh-pages/img. I used this tool: https://github.com/bast/gitink. I wrote the latter tool long time ago when I did not know how to write a well structured code :-) so it is not very nice on the inside but does the job and my plan is to eventually rewrite it but anyway :-)

**Comment by mprinc** [comment]
Thank you Radovan!
I think it fulfills its purpose well! :)
